### ISSUE TITLE
[Bug] custom function won't recognize functions imported from libraries

### ISSUE THREAD

**Issue by tombistolas** [EddLabs/eddington#118]
first image without the use of math library works (the program returns a fit when used in GUI) 
the second image does not work (important to say that I tried many different variations of using the import and the 2nd function. 

![image](https://user-images.githubusercontent.com/73796375/97812657-78580b80-1c8b-11eb-8869-3774e71a8f3c.png)
![image](https://user-images.githubusercontent.com/73796375/97812679-a5a4b980-1c8b-11eb-8bab-7f7d2172d61e.png)

**Comment by saroad2** [comment]
This is not a bug in Eddington, but a misconception about how the optimization work.
The optimization algorithm uses **vectors calculation** in order to optimize the results. The methods in the `math` package except **scalars**, and this is the reason it doesn't work. If you use `numpy.sqrt` (which *do* excepts vectors) instead of `math.sqrt`, it would work. full code example:

```python
import numpy as np

from eddington import fitting_function


@fitting_function(n=2)
def try37(a, x):
    def funWithNums(x):
        return np.sqrt(x)
    return a[0] * funWithNums(x) + a[1]
```

In order to make it clearer for other users, I will add this short explanation in the documentation.

**Comment by tombistolas** [comment]
Hey, this is not entirely helping since my intentions were to use the
scipy.integrate library which requires the use of different function in
order to work and that didnt work so i tried to simplify my code to find
the root of the problem. So the error i uploaded was just an simplified
example of bigger problem
