### ISSUE TITLE
[Bug] Fitting a line only between 2 points

### ISSUE THREAD

**Issue by asafharel** [EddLabs/eddington#120]
**Describe the bug**
When trying to fit a linear line between **only** 2 points, I will get a ZeroDivisionError, since the degrees of freedom is 0, and the program tries to calculate the chi2_reduced.

**Expected behaviour**
The program will be able to fit the linear line.

**Context**
The error happens in the fitting_result.py file, in line 51.

 - Eddington version: 0.0.21
 - Python version: 3.8.5
 - Operating system: MacOS Catalina 10.15.7

**Comment by saroad2** [comment]
Hey @asafharel , Thanks for the report.

The scenario you described is actually as-designed. Eddington is a fitting and optimizing platform. It tries to fit the data to a model of your choosing. In order to do so, it needs more data records than the number of parameters. Otherwise, it can't tell if it succeeded or not in fitting the data.

It's true that 2 records should be enough to find a line between two points, but when using noised valued, it is not, that's because you can't evaluate the error of the fitting (ie, the data can't be fitted). You **can** however, calculate the line between two points without using Eddington, using this equation:

![CodeCogsEqn](https://user-images.githubusercontent.com/19425795/99886244-91792a00-2c43-11eb-8942-1f72efc01238.gif)

but again, this is **not** a fitting result because you can't use this evaluation to estimate the error.
